### PR TITLE
script dynatrace problem notification

### PR DESCRIPTION
**Pull request by alipatton10**
hardcoded to Default alerting profile as ID is not available via api

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
thanks for the PR @alipatton10 
could you please change the branch to `develop` instead of `master`?

**Comment by jetzlstorfer** [comment]
I've changed the branch for you. Please resolve the conflict and I'm happy to accept the PR

**Comment by alipatton10** [comment]
The only file we actually need is deplyDynatraceNotification.sh  so you can probably just delete the others

**Comment by alipatton10** [comment]
Opened new PR for develop branch

**Pull request closed without merging**
